version: 2.1
orbs:
  artifactory: circleci/artifactory@volatile

workflows:
  build_publish_consume:
    jobs:
      - artifactory/docker-publish:
          name: Standard Docker Build & Publish
          docker-registry: orbdemos-docker.jfrog.io
          repository: docker
          build-name: demo-ci-build-image
          docker-tag: orbdemos-docker.jfrog.io/ci-build-image:latest
      - consume_it:
          requires:
            - 'Standard Docker Build & Publish'
  docker_with_jib:
    jobs:
      - artifactory/docker-publish:
          name: Docker Publish with Jib
          docker-registry: orbdemos-docker.jfrog.io
          repository: docker
          build-name: demo-spring-boot-jib
          docker-tag: orbdemos-docker.jfrog.io/spring-boot:1.0-${CIRCLE_BUILD_NUM}
          docker-steps:
            - run: echo ${DOCKERTAG}
            - run: cd jib && ./mvnw compile jib:exportDockerContext -s .mvn/wrapper/settings.xml
            - run: docker build -t ${DOCKERTAG} jib/target/jib-docker-context


jobs:
  consume_it:
    docker:
      - image: orbdemos-docker.jfrog.io/ci-build-image:latest
        auth:
          username: circleci
          password: ${ARTIFACTORY_API_KEY}
    steps:
      - run: ls
      - run: bash demo.bash