version: 2.1
orbs:
  artifactory: circleci/artifactory@0.0.5

workflows:
  build_publish_consume:
    jobs:
      - artifactory/docker-publish:
          name: Docker Build & Publish
          docker-registry: orbdemos-docker.jfrog.io
          repository: docker
          docker-tag: orbdemos-docker.jfrog.io/ci-build-image:latest
          dependency-steps:
            - run: jfrog rt dl local-generic/demo.bash\
                   --build-name=${CIRCLE_PROJECT_REPONAME}\
                   --build-number=${CIRCLE_BUILD_NUM}
      - consume_it:
          requires:
            - 'Docker Build & Publish'

jobs:
  consume_it:
    docker:
      - image: orbdemos-docker.jfrog.io/ci-build-image:latest
        auth:
          username: circleci
          password: ${ARTIFACTORY_API_KEY}
    steps:
      - run: pwd && ls #just confirm file is not checked out, but part of image
      - run: demo
