version: 2.1
orbs:
  artifactory: circleci/artifactory@0.0.4
  hello:       circleci/hello-build@0.0.7

workflows:
  custom_docker:
    jobs:
      - artifactory/docker-publish:
          name: Docker Publish with Google Jib
          docker-registry: orbdemos-docker.jfrog.io
          repository: docker
          build-name: demo-spring-boot-jib
          docker-tag: orbdemos-docker.jfrog.io/spring-boot:1.0-${CIRCLE_BUILD_NUM}
          docker-steps:
            - run: echo ${DOCKERTAG}
            - restore_cache:
                keys:
                  - demo-mvn-V2-{{ checksum "jib/pom.xml" }}           
            - run: cd jib && jfrog rt mvn "compile jib:exportDockerContext -s .mvn/wrapper/settings.xml" --build-name=demo-spring-boot-jib --build-number=${CIRCLE_BUILD_NUM}
            - run: docker build -t ${DOCKERTAG} jib/target/jib-docker-context
            - save_cache:
                paths:
                  - ~/.m2
                key: demo-mvn-V2-{{ checksum "jib/pom.xml" }}
      - approval:
          type: approval
          requires: 
            - "Docker Publish with Google Jib"
      - hello/hello-build:
          name: Mock Deployment
          requires: 
            - approval
